spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddd?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: root
    password: rlafhrdnjs1
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace

discord:
  webhook:
    url: https://discord.com/api/webhooks
    error-channel-path: /1327866249559933051/sjsfAlTx0VxSPjD5FIwje9FAudDHVpdKZ_TZAFcaaiLSG9cWT1fCvRtcEnyD71-YuYNj