spring:
  profiles:
    default: local

server:
  servlet:
    context-path: /api
  shutdown: graceful
  error:
    include-binding-errors: always
    include-message: always
    include-exception: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  override-with-generic-response: true
  writer-with-order-by-keys: true